"""Builds ``_data/impact/techniques.json``.

This file is the taxonomy the whole pipeline reads: which tools belong to the
SQLancer umbrella, which techniques originated in SQLancer, which acronyms are
ambiguous enough to need corroborating context, and which techniques are
deliberately out of scope.

It is generated by a script rather than hand-written JSON so that the aliases,
context terms and evidence stay in one reviewable place, but the generated file
is the artefact the collectors consume.
"""

from __future__ import annotations

from .. import config
from ..util import now

TAXONOMY_VERSION = "taxonomy-v2"

_SEEN = "2026-09-06T00:00:00Z"

# Terms that establish a match is about database testing rather than an
# unrelated use of the same acronym (TLP is also Thread Level Parallelism,
# Transport Layer Protocol, a Linux power tool; PQS is also a chemistry suite).
DB_CONTEXT = [
    "sqlancer", "dbms", "database", "sql", "query", "oracle", "logic bug",
    "metamorphic", "fuzz", "test oracle", "optimizer", "optimiser",
]

TECHNIQUES = [
    {
        "id": "pqs",
        "names": ["PQS", "Pivoted Query Synthesis", "pivoted query synthesis"],
        "display_name": "Pivoted Query Synthesis (PQS)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2020,
        "origin_paper": {
            "title": "Testing Database Engines via Pivoted Query Synthesis",
            "venue": "OSDI 2020",
            "year": 2020,
            "url": "https://www.usenix.org/system/files/osdi20-rigger.pdf",
            "doi": None,
            "arxiv_id": "2001.04174",
            "s2_paper_id": None,
            "is_citation_seed": True,
        },
        "ambiguous_acronym": True,
        "required_context_terms": DB_CONTEXT,
        "negative_context_terms": ["photoelectron", "quantum", "parallel quantum"],
        "description": (
            "Selects a random row, the pivot row, and generates a query that is "
            "guaranteed to fetch it. If the row is missing from the result set, a "
            "bug has been found."
        ),
    },
    {
        "id": "norec",
        "names": [
            "NoREC",
            "Non-optimizing Reference Engine Construction",
            "Non-Optimizing Reference Engine Construction",
            "non-optimizing reference engine construction",
        ],
        "display_name": "Non-optimizing Reference Engine Construction (NoREC)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2020,
        "origin_paper": {
            "title": (
                "Detecting optimization bugs in database engines via "
                "non-optimizing reference engine construction"
            ),
            "venue": "ESEC/FSE 2020",
            "year": 2020,
            "url": "https://arxiv.org/abs/2007.08292",
            "doi": "10.1145/3368089.3409710",
            "arxiv_id": "2007.08292",
            "s2_paper_id": "55a4e4a42cd86fac55491d089d07d04f09dcf957",
            "is_citation_seed": True,
        },
        "ambiguous_acronym": False,
        "required_context_terms": [],
        "negative_context_terms": [],
        "description": (
            "Translates a query that the DBMS is likely to optimise into one for "
            "which hardly any optimisation applies, then compares the two result "
            "sets. A mismatch indicates an optimisation bug."
        ),
    },
    {
        "id": "tlp",
        "names": [
            "TLP",
            "Ternary Logic Partitioning",
            "ternary logic partitioning",
            "query partitioning",
        ],
        "display_name": "Ternary Logic Partitioning (TLP)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2020,
        "origin_paper": {
            "title": "Finding bugs in database systems via query partitioning",
            "venue": "OOPSLA 2020",
            "year": 2020,
            "url": "https://dl.acm.org/doi/pdf/10.1145/3428279",
            "doi": "10.1145/3428279",
            "arxiv_id": None,
            "s2_paper_id": "d69216947188267d5537ee0f0501b2d960ecc457",
            "is_citation_seed": True,
        },
        "ambiguous_acronym": True,
        "required_context_terms": DB_CONTEXT,
        "negative_context_terms": [
            "thread level parallelism", "thread-level parallelism",
            "transport layer", "tlp-stat", "laptop", "power management",
        ],
        "description": (
            "Partitions a query into three partitioning queries whose combined "
            "results must match the original query's result set. Unlike NoREC and "
            "PQS it also reaches advanced features such as aggregate functions."
        ),
    },
    {
        "id": "qpg",
        "names": ["QPG", "Query Plan Guidance", "query plan guidance"],
        "display_name": "Query Plan Guidance (QPG)",
        "kind": "test_input_generation",
        "sqlancer_originated": True,
        "introduced_year": 2023,
        "origin_paper": {
            "title": "Testing Database Systems via Query Plan Guidance",
            "venue": "ICSE 2023",
            "year": 2023,
            "url": "https://arxiv.org/pdf/2312.17510",
            "doi": None,
            "arxiv_id": "2312.17510",
            "s2_paper_id": None,
            "is_citation_seed": True,
        },
        "ambiguous_acronym": True,
        "required_context_terms": DB_CONTEXT,
        "negative_context_terms": [],
        "description": (
            "Feedback-guided test input generation that mutates the database state "
            "when no new query plans have been observed, on the insight that query "
            "plans capture whether interesting behaviour is being exercised."
        ),
    },
    {
        "id": "cert",
        "names": [
            "CERT",
            "Cardinality Estimation Restriction Testing",
            "cardinality estimation restriction testing",
        ],
        "display_name": "Cardinality Estimation Restriction Testing (CERT)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2024,
        "origin_paper": {
            "title": (
                "Cardinality Estimation Restriction Testing: Finding Performance "
                "Issues in Database Systems"
            ),
            "venue": "ICSE 2024",
            "year": 2024,
            "url": "https://arxiv.org/pdf/2306.00355",
            "doi": None,
            "arxiv_id": "2306.00355",
            "s2_paper_id": None,
            "is_citation_seed": True,
        },
        "ambiguous_acronym": True,
        "required_context_terms": DB_CONTEXT + ["cardinality", "performance issue"],
        # "cert" is overwhelmingly TLS in a database tracker; without these,
        # every SSL certificate bug in PostgreSQL and CockroachDB reads as a
        # CERT finding.
        "negative_context_terms": [
            "certificate", "cert.org", "us-cert", "x.509", "x509", "ssl",
            "tls", "https", "ca cert", "root cert", "crl", "keystore",
            "truststore", "openssl", "self-signed", "cert-manager",
            "auth_method", "sslmode",
        ],
        "description": (
            "Derives a more restrictive query whose estimated cardinality must not "
            "exceed the original's. A violation points at a performance issue. The "
            "only SQLancer oracle aimed at performance rather than correctness."
        ),
    },
    {
        "id": "dqp",
        "names": ["DQP", "Differential Query Plan", "differential query plans"],
        "display_name": "Differential Query Plans (DQP)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2024,
        "origin_paper": {
            "title": "Keep It Simple: Testing Databases via Differential Query Plans",
            "venue": "SIGMOD 2024",
            "year": 2024,
            "url": "https://dl.acm.org/doi/pdf/10.1145/3654991",
            "doi": "10.1145/3654991",
            "arxiv_id": None,
            "s2_paper_id": "63b32cbfc5e6ab0043715a9adcf6ad1944c9ba49",
            "is_citation_seed": True,
        },
        "ambiguous_acronym": True,
        "required_context_terms": DB_CONTEXT,
        "negative_context_terms": [],
        "description": (
            "Forces the DBMS to execute the same query using different query plans "
            "and compares the results, which must agree."
        ),
    },
    {
        "id": "coddtest",
        "names": [
            "CODDTest",
            "Constant Optimization Driven Database System Testing",
            "constant optimization driven database system testing",
        ],
        "display_name": "Constant-Optimization-Driven Testing (CODDTest)",
        "kind": "test_oracle",
        "sqlancer_originated": True,
        "introduced_year": 2025,
        "origin_paper": {
            "title": (
                "Constant Optimization Driven Database System Testing"
            ),
            "venue": "SIGMOD 2025",
            "year": 2025,
            "url": "https://arxiv.org/abs/2501.11046",
            "doi": None,
            "arxiv_id": "2501.11046",
            "s2_paper_id": None,
            "is_citation_seed": True,
        },
        "ambiguous_acronym": False,
        "required_context_terms": [],
        "negative_context_terms": [],
        "description": (
            "Borrows constant folding from compiler testing: subexpressions are "
            "replaced by their computed constants and the result must not change."
        ),
    },
]

FINDERS = [
    {
        "id": "sqlancer",
        "display_name": "SQLancer",
        "names": ["SQLancer", "sqlancer"],
        "umbrella_member": True,
        "repository": "https://github.com/sqlancer/sqlancer",
        "paper": None,
        "description": (
            "The main SQLancer tool: hand-written SQL generators for a large set of "
            "database systems, combined with the test oracles listed above."
        ),
    },
    {
        "id": "sqlancer_pp",
        "display_name": "SQLancer++",
        "names": ["SQLancer++", "SQLancerPlusPlus", "SQLancer PP"],
        "umbrella_member": True,
        "repository": "https://github.com/suyZhong/SQLancerPlusPlus",
        "paper": {
            "title": "Scaling Automated Database System Testing",
            "venue": "ASPLOS 2026",
            "year": 2026,
            "url": "https://doi.org/10.1145/3779212.3790215",
            "doi": "10.1145/3779212.3790215",
        },
        "description": (
            "Scales automated testing to database systems for which no bespoke "
            "SQLancer implementation exists, by adaptively discovering which SQL "
            "features the system under test supports."
        ),
    },
    {
        "id": "shqvel",
        "display_name": "ShQveL",
        "names": ["ShQveL", "Shqvel"],
        "umbrella_member": True,
        "repository": "https://github.com/suyZhong/SQLancerPlusPlus",
        "paper": {
            "title": "Automated Database Testing via LLM-Synthesized SQL Features",
            "venue": None,
            "year": 2025,
            "url": "https://arxiv.org/abs/2505.02012",
            "doi": "10.48550/arxiv.2505.02012",
        },
        "description": (
            "Augments SQLancer-style testing with SQL feature fragments synthesised "
            "by a large language model, reaching features the hand-written "
            "generators do not cover."
        ),
    },
]

EXCLUDED = [
    {
        "id": "dqe",
        "names": ["DQE", "Differential Query Execution",
                  "differential query execution"],
        "display_name": "Differential Query Execution (DQE)",
        "reason": (
            "DQE was developed independently of SQLancer by Song et al. and "
            "published at ICSE 2023; its SQLancer implementation arrived later "
            "as a contributed pull request. Implementing a technique is not "
            "originating it, so DQE-attributed bugs are not counted as SQLancer "
            "findings and papers citing the DQE publication are not treated as "
            "citing SQLancer."
        ),
        "evidence": [
            {
                "source_url": "https://github.com/sqlancer/sqlancer/blob/main/README.md",
                "source_type": "documentation",
                "excerpt": (
                    "| Differential Query Execution (DQE)                    "
                    "          | ICSE 2023     | "
                    "[Paper](https://ieeexplore.ieee.org/document/10172736) "
                    "[Code](https://github.com/sqlancer/sqlancer/pull/1251)"
                ),
                "excerpt_is_verbatim": True,
                "note": (
                    "SQLancer's own README credits DQE to an external ICSE 2023 "
                    "publication and links its implementation as a pull request "
                    "contributed to SQLancer."
                ),
                "content_sha256": (
                    "sha256:e5f5180fefc22551e27d9fb83cb9337cad8625677ee6185f"
                    "e8c312715e154042"
                ),
                "retrieved_at": _SEEN,
                "first_seen": _SEEN,
                "last_verified": _SEEN,
            }
        ],
    },
    {
        "id": "eet",
        "names": ["EET", "Equivalent Expression Transformation"],
        "display_name": "Equivalent Expression Transformation (EET)",
        "reason": (
            "EET was introduced by Jiang and Su at OSDI 2024, independently of "
            "SQLancer. SQLancer later gained an EET oracle, but implementing a "
            "technique is not originating it, so bugs found with EET are not "
            "counted as SQLancer findings."
        ),
        "evidence": [
            {
                "source_url": (
                    "https://github.com/sqlancer/sqlancer/blob/main/src/sqlancer/"
                    "common/oracle/EETOracle.java"
                ),
                "source_type": "github_code",
                "excerpt": (
                    "EET (Equivalent Expression Transformation) oracle, based on "
                    "\"Detecting Logic Bugs in Database Engines via Equivalent\n * "
                    "Expression Transformation\" (Jiang &amp; Su, OSDI'24)."
                ),
                "excerpt_is_verbatim": True,
                "note": (
                    "Class-level Javadoc of SQLancer's own EET oracle, crediting the "
                    "technique to an external publication."
                ),
                "content_sha256": (
                    "sha256:e61be0c83848f4b428ece8faa2aa9b0b006559d13c708eb"
                    "b0285c4fe8254648d"
                ),
                "retrieved_at": _SEEN,
                "first_seen": _SEEN,
                "last_verified": _SEEN,
            }
        ],
    },
]

# A paper co-authored by one of these is the project's own work, not external
# work building on SQLancer. Matched as a whole word against each author name.
PROJECT_AUTHORS = ["Rigger"]

# People who found bugs as part of the project rather than as outside adopters.
# The TEST lab's members are read from its people page during collection, so
# only contributors who are not on it need listing here.
PROJECT_CONTRIBUTORS = [
    {"name": "Manuel Rigger", "github": "mrigger", "role": "Project author"},
    {"name": "Zhenglin Li", "github": "ZhengLin-Li",
     "role": "Google Summer of Code 2023 contributor"},
    {"name": "Zhenglin Li", "github": "zhenglin-charlie-li",
     "role": "Google Summer of Code 2023 contributor"},
    {"name": "Yutan Yang", "github": "ColinYoungTaro",
     "role": "Google Summer of Code 2023 contributor"},
]

# Papers written as part of the SQLancer project that are not already named
# above as a technique's origin paper or a tool's paper. Both entries below are
# also covered by PROJECT_AUTHORS; they are listed anyway so the decision
# survives a change to that list.
PROJECT_PUBLICATIONS = [
    {
        "title": ("Validating Database System Isolation Level Implementations "
                  "with Version Certificate Recovery"),
        "doi": "10.1145/3627703.3650080",
        "arxiv_id": None,
        "s2_paper_id": None,
        "year": 2024,
        "venue": "EuroSys 2024",
        "reason": ("Project publication: work by the SQLancer authors applying "
                   "the PQS idea to isolation-level validation."),
    },
    {
        "title": "Bringing Order to Practical Validation of Database Isolation Levels",
        "doi": "10.1145/3797871",
        "arxiv_id": None,
        "s2_paper_id": None,
        "year": 2026,
        "venue": "ACM Transactions on Computer Systems",
        "reason": ("Project publication: the journal version of the EuroSys "
                   "2024 isolation-level paper by the same authors."),
    },
]

BUG_SYMPTOMS = [
    {"id": "logic", "display_name": "Logic bug",
     "description": "The DBMS returned an incorrect result set."},
    {"id": "error", "display_name": "Unexpected error",
     "description": "The DBMS raised an internal or otherwise unexpected error."},
    {"id": "crash", "display_name": "Crash",
     "description": "The DBMS process terminated abnormally."},
    {"id": "hang", "display_name": "Hang",
     "description": "The DBMS stopped making progress."},
    {"id": "performance", "display_name": "Performance issue",
     "description": "The DBMS produced a correct result far less efficiently than it could."},
    {"id": "unknown", "display_name": "Unclassified",
     "description": "The report does not record how the bug manifested."},
]


def build() -> dict:
    return {
        "schema_version": "1.0.0",
        "taxonomy_version": TAXONOMY_VERSION,
        "finders": FINDERS,
        "sqlancer_techniques": TECHNIQUES,
        "project_authors": PROJECT_AUTHORS,
        "project_contributors": PROJECT_CONTRIBUTORS,
        "project_publications": PROJECT_PUBLICATIONS,
        "excluded_techniques": EXCLUDED,
        "bug_symptoms": BUG_SYMPTOMS,
    }


def main() -> int:
    changed = config.write_json(config.DATA_FILES["techniques"], build())
    print(f"techniques.json: {'updated' if changed else 'unchanged'} "
          f"({len(TECHNIQUES)} techniques, {len(FINDERS)} finders) at {now()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
